// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace DAL.CompiledModels
{
    public partial class KorfinContextModel
    {
        partial void Initialize()
        {
            var ost = OstEntityType.Create(this);
            var user = UserEntityType.Create(this);

            OstEntityType.CreateForeignKey1(ost, user);

            OstEntityType.CreateAnnotations(ost);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "7.0.5");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
