// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace DAL.CompiledModels
{
    [DbContext(typeof(KorfinContext))]
    public partial class KorfinContextModel : RuntimeModel
    {
        static KorfinContextModel()
        {
            var model = new KorfinContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static KorfinContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
